2025-08-26 13:00:57,241 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018358AD3770>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /graphql
2025-08-26 13:01:01,529 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018358B90A50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /graphql
2025-08-26 13:01:06,021 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018358B90B90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /graphql
2025-08-26 13:01:10,091 - Error processing order reminders: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018358B362C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-08-26 13:02:29,101 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002236FF4F770>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /graphql
2025-08-26 13:02:33,679 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002236FFF0A50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /graphql
2025-08-26 13:02:38,148 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002236FFF0B90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /graphql
2025-08-26 13:02:42,241 - Error processing order reminders: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002236FFB22C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-08-26 13:03:28,937 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002E799EEF770>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /graphql
2025-08-26 13:03:33,208 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002E799FA0A50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /graphql
2025-08-26 13:03:37,702 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002E799FA0B90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /graphql
2025-08-26 13:03:41,766 - Error processing order reminders: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002E799F522C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-08-26 13:05:11,754 - Error processing order reminders: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /graphql (Caused by ResponseError('too many 500 error responses'))
2025-08-26 13:09:46,303 - Connection test failed: 500 Server Error: Internal Server Error for url: http://localhost:8000/graphql/
